name: where_should_you_live
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.6.4
  flutter_svg: ^2.0.4
  liquid_swipe: ^3.1.0
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.19
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true


assets:
  - assets/Asset 1.svg
  - assets/Cloud 2.svg
  - assets/Cloud 1.svg

fonts:
  - family: Segoe UI
    fonts:
      - asset: assets/Segoe UI.ttf