// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyD9fpXBtPRU8X10M6uKuMbVvZgpQzM25CE',
    appId: '1:700216601439:web:0430dac8f269b9f530a4ea',
    messagingSenderId: '700216601439',
    projectId: 'profileapp-de82a',
    authDomain: 'profileapp-de82a.firebaseapp.com',
    storageBucket: 'profileapp-de82a.appspot.com',
    measurementId: 'G-4S0Q43M1R3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr5jJh_2Z4Tu-FiOY7dMLTh3FU-AnQm2s',
    appId: '1:700216601439:ios:d72d19be00322edf30a4ea',
    messagingSenderId: '700216601439',
    projectId: 'profileapp-de82a',
    storageBucket: 'profileapp-de82a.appspot.com',
    iosClientId: '700216601439-o6smegf6sd41b301tegf4vp86j893g3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.userapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr5jJh_2Z4Tu-FiOY7dMLTh3FU-AnQm2s',
    appId: '1:700216601439:ios:d72d19be00322edf30a4ea',
    messagingSenderId: '700216601439',
    projectId: 'profileapp-de82a',
    storageBucket: 'profileapp-de82a.appspot.com',
    iosClientId: '700216601439-o6smegf6sd41b301tegf4vp86j893g3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.userapp',
=======
    apiKey: 'AIzaSyBCDnynd1XzNWyN0k6QmZAMulUH4Mewgd0',
    appId: '1:625745952057:web:d73a9b9538fac51cabbce8',
    messagingSenderId: '625745952057',
    projectId: 'whereshouldyoulive-1e51b',
    authDomain: 'whereshouldyoulive-1e51b.firebaseapp.com',
    databaseURL: 'https://whereshouldyoulive-1e51b-default-rtdb.firebaseio.com',
    storageBucket: 'whereshouldyoulive-1e51b.appspot.com',
    measurementId: 'G-D5RXB8WN9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBx6ClpNicDmIqP9eNtcoknpxDGxEiDig',
    appId: '1:625745952057:android:b1be33636ef47cbcabbce8',
    messagingSenderId: '625745952057',
    projectId: 'whereshouldyoulive-1e51b',
    databaseURL: 'https://whereshouldyoulive-1e51b-default-rtdb.firebaseio.com',
    storageBucket: 'whereshouldyoulive-1e51b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztBuO_eyaAi1Bcw2dr3m2JGMQ207-0IU',
    appId: '1:625745952057:ios:f15af43c9329b106abbce8',
    messagingSenderId: '625745952057',
    projectId: 'whereshouldyoulive-1e51b',
    databaseURL: 'https://whereshouldyoulive-1e51b-default-rtdb.firebaseio.com',
    storageBucket: 'whereshouldyoulive-1e51b.appspot.com',
    iosClientId: '625745952057-gfagi3a81cgdrqpquv8eei7if5ighv7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.whereShouldYouLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAztBuO_eyaAi1Bcw2dr3m2JGMQ207-0IU',
    appId: '1:625745952057:ios:f15af43c9329b106abbce8',
    messagingSenderId: '625745952057',
    projectId: 'whereshouldyoulive-1e51b',
    databaseURL: 'https://whereshouldyoulive-1e51b-default-rtdb.firebaseio.com',
    storageBucket: 'whereshouldyoulive-1e51b.appspot.com',
    iosClientId: '625745952057-gfagi3a81cgdrqpquv8eei7if5ighv7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.whereShouldYouLive',
>>>>>>> cc754e5be13cd74889f7e0d45593ae1eef0a72bb
  );
}
