# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogintoforgotpassword():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logintoforgotpassword(self):
    # Test name: log in to forgot password
    # Step # | name | target | value | comment
    # 1 | open | http://localhost:49975/#/SignUpPage |  | 
    self.driver.get("http://localhost:49975/#/SignUpPage")
    # 2 | setWindowSize | 1296x696 |  | 
    self.driver.set_window_size(1296, 696)
    # 3 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 4 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 5 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 6 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
  
