# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOnbordingpagetologin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_onbordingpagetologin(self):
    # Test name: onbording page to log in
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://localhost:49975//")
    # 2 | setWindowSize | 1296x696 |  | 
    self.driver.set_window_size(1296, 696)
    # 3 | mouseDownAt | css=flt-glass-pane | 334,335 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 4 | mouseMoveAt | css=flt-glass-pane | 334,335 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseUpAt | css=flt-glass-pane | 334,335 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 6 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 7 | mouseDownAt | css=flt-glass-pane | 446,323 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 8 | mouseMoveAt | css=flt-glass-pane | 446,323 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | mouseUpAt | css=flt-glass-pane | 446,323 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 10 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 11 | mouseDownAt | css=flt-glass-pane | 561,495 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 12 | mouseMoveAt | css=flt-glass-pane | 561,495 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 13 | mouseUpAt | css=flt-glass-pane | 561,495 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 14 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 15 | mouseDownAt | css=flt-glass-pane | 906,402 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 16 | mouseMoveAt | css=flt-glass-pane | 906,402 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | mouseUpAt | css=flt-glass-pane | 906,402 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 18 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 19 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 20 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 21 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 22 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
  
