# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOpenfilterratecity2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_openfilterratecity2(self):
    # Test name: open filter rate city 2
    # Step # | name | target | value | comment
    # 1 | open | http://localhost:61023/#/SignUpPage |  | 
    self.driver.get("http://localhost:61023/#/SignUpPage")
    # 2 | setWindowSize | 1296x696 |  | 
    self.driver.set_window_size(1296, 696)
    # 3 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 4 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 5 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 6 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 7 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 8 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 9 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 10 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 11 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 12 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 13 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 14 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 15 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 16 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 17 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 18 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 19 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 20 | mouseDownAt | css=flt-glass-pane | 157,105 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 21 | mouseMoveAt | css=flt-glass-pane | 157,105 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 22 | mouseUpAt | css=flt-glass-pane | 157,105 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 23 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 24 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 25 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 26 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 27 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 28 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 29 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 30 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 31 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 32 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 33 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 34 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 35 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 36 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 37 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 38 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
  
