# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignupusinggoogleaccout():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_signupusinggoogleaccout(self):
    # Test name: sign_up_using_google_accout
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://localhost:49975//")
    # 2 | setWindowSize | 1296x696 |  | 
    self.driver.set_window_size(1296, 696)
    # 3 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 4 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 5 | click | css=flt-glass-pane |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 6 | storeWindowHandle | root |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 7 | selectWindow | handle=${win6614} |  | 
    self.vars["win6614"] = self.wait_for_window(2000)
    # 8 | click | css=.JDAKTe:nth-child(3) .w1I7fb |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 9 | close |  |  | 
    self.driver.switch_to.window(self.vars["win6614"])
    # 10 | selectWindow | handle=${root} |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".JDAKTe:nth-child(3) .w1I7fb").click()
    # 11 | click | css=flt-glass-pane |  | 
    self.driver.close()
    # 12 | click | css=flt-glass-pane |  | 
    self.driver.switch_to.window(self.vars["root"])
    # 13 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    # 14 | click | css=flt-glass-pane |  | 
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
    self.driver.find_element(By.CSS_SELECTOR, "flt-glass-pane").click()
  
